version: "3"

networks:
  web_net:
    driver: bridge

volumes:
  data:
  images:

services:
  db:
    image: mysql:8.0
    container_name: database
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: always
    volumes:
      - data:/var/lib/mysql
      - ./Backend/config/mysql:/docker-entrypoint-initdb.d
    networks:
      - web_net

  backend:
    build:
      context: ./Backend
    container_name: backend
    environment:
      - SETTINGS_PATH=${SETTINGS_PATH}
      - PAT=${PAT}
      - CID=${CID}
      - SAT=${SAT}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - ADMIN_LOGIN=${ADMIN_LOGIN}
      - ADMIN_PASSWD=${ADMIN_PASSWD}
      - ADMIN_MAIL=${ADMIN_MAIL}
      - API_URL=${API_URL}
      - SECRET_KEY=${SECRET_KEY}
    ports: 
      - "5000:5000"
      - "4444:4444"
    restart: always
    depends_on:
      - db
    volumes:
      - ./Backend/app:/app/app
      - ./Backend/config/flask:/app/config
      - ./Backend/migrations:/app/migrations
      - images:/app/app/static/images
    entrypoint: /app/entrypoint.sh
    networks:
      - web_net
    stdin_open: true
    tty: true
